### ISSUE TITLE
Snowboard Not Themeing Offloaded Apps

### ISSUE THREAD

**Issue by gideongrinberg** [nahtedetihw/SnowboardWIKI#1]
Basically what the title says. This maybe can be fixed, it's kind of annoying. I can't upload a video, but [on the Discord](https://discord.com/channels/366171285715157003/574132599539236864/772223659279908914) if you need more elaboration as to what I mean.

**Comment by SparkDev97** [comment]
This is known, and may be changed in the future - but is not planned at the moment.

Please keep to posting on the discord server, rather than here - thank you.

**Comment by gideongrinberg** [comment]
Sorry @SparkDev97. Thanks.
