### ISSUE TITLE
How to theme sounds?

### ISSUE THREAD

**Issue by 1333481** [nahtedetihw/SnowboardWIKI#2]
There is no documentation on sounds for ui

**Comment by JDagsa** [comment]
Just go and make a folder in your theme's root directory (Theme.theme/) called UISounds, then add these sounds, and make sure they are in a .caf format:

- ReceivedMessage.caf
- SentMessage.caf
- Tock.caf
- connect_power.caf
- key_press_click.caf
- key_press_delete.caf
- key_press_modifier.caf
- keyboard_press_clear.caf
- keyboard_press_delete.caf
- keyboard_press_normal.caf
- lock.caf
- photoShutter.caf
- tink.caf

**Comment by nahtedetihw** [comment]
https://github.com/nahtedetihw/SnowboardWIKI/wiki/UISounds
